export const gymTypes = [
  {
    id: '24h',
    name: '24hジム（マシン中心）',
    price_range: '月額 6,000〜12,000円',
    fit_reasons: ['時間が不規則でも通いやすい', '低コストで始めやすい'],
    cautions: ['メニュー設計が不安だと迷いやすい', '混雑時間帯は待ちが発生'],
    pain_considerations: ['初心者ガイダンスの有無を確認', '痛みが出たら中断'],
    checklist_items: [
      'スタッフ滞在時間/初心者案内',
      '混雑ピークの様子',
      'マシンの使い方表示',
      'フリーウエイトエリアの雰囲気',
      '退会/休会条件',
    ],
  },
  {
    id: 'fitness',
    name: '総合フィットネスクラブ',
    price_range: '月額 8,000〜18,000円',
    fit_reasons: ['クラスで楽しく続けたい', 'プール/サウナなども活用したい'],
    cautions: ['利用時間が限られることがある', '使わない設備が多いと割高'],
    pain_considerations: ['低負荷クラスの有無を確認'],
    checklist_items: [
      '通える時間帯のプログラム',
      '初心者向け枠の有無',
      '館内導線（混雑/待ち）',
      'インストラクターの声かけ',
      'オプション費用',
    ],
  },
  {
    id: 'public',
    name: '公営ジム（都度利用）',
    price_range: '1回 200〜700円',
    fit_reasons: ['固定費が不安な人に合う', 'まずはお試しで始めたい'],
    cautions: ['指導/サポートが少ないことが多い', '設備が最新でない場合あり'],
    pain_considerations: ['軽い有酸素や可動域づくり中心に'],
    checklist_items: [
      '初回講習の有無',
      'マシンの種類',
      '混雑/利用制限',
      '更衣室・ロッカーの使い勝手',
    ],
  },
  {
    id: 'personal',
    name: 'パーソナルジム（マンツーマン）',
    price_range: '1回 7,000〜15,000円',
    fit_reasons: ['何をすれば良いか分からない', '最短で成果を出したい'],
    cautions: ['料金が高め', 'トレーナーの質に差がある'],
    pain_considerations: ['痛みが出ない範囲での調整方針を確認'],
    checklist_items: [
      'カウンセリングで痛みを聞いてくれるか',
      'フォーム指導が具体的か',
      '無理な食事制限を強要しないか',
      '予約の取りやすさ/キャンセル規定',
      '卒業後の自走支援',
    ],
  },
  {
    id: 'semipersonal',
    name: 'セミパーソナル（少人数）',
    price_range: '月額 15,000〜40,000円',
    fit_reasons: ['指導がほしいが費用は抑えたい', '大人数は苦手'],
    cautions: ['参加者次第でフォロー量が変わる', '予約枠が埋まると通えない'],
    pain_considerations: ['痛みがある前提で代替案が出せるか'],
    checklist_items: [
      '定員とトレーナー比率',
      '個別対応の範囲',
      '予約の取りやすさ',
      '初心者が置いていかれない雰囲気',
    ],
  },
  {
    id: 'studio',
    name: 'スタジオ系（ヨガ等）',
    price_range: '月額 8,000〜16,000円',
    fit_reasons: ['クラスで習慣化したい', '低〜中負荷から始めたい'],
    cautions: ['筋力アップ中心だと物足りない', '人気枠は予約が取りづらい'],
    pain_considerations: ['やさしいクラスや代替ポーズ案内の有無'],
    checklist_items: [
      '難易度表記の分かりやすさ',
      '代替案を出す文化',
      '予約/キャンセルのしやすさ',
      '更衣/シャワーの要否',
    ],
  },
  {
    id: 'combat',
    name: '格闘技フィットネス',
    price_range: '月額 9,000〜16,000円',
    fit_reasons: ['楽しく続けたい', 'ストレス解消を重視したい'],
    cautions: ['フォームが雑だと痛みにつながることがある', '混雑時は指導が薄くなる'],
    pain_considerations: ['痛みのある部位に配慮できるか確認'],
    checklist_items: [
      '初心者向け導入があるか',
      '強度調整の仕組み',
      'クラスの雰囲気',
      'フォーム指導の密度',
    ],
  },
  {
    id: 'conditioning',
    name: 'コンディショニングジム',
    price_range: '月額 10,000〜40,000円',
    fit_reasons: ['痛み/不調に配慮しながら習慣化したい', '身体の使い方を学びたい'],
    cautions: ['提供内容の幅が広く相性差がある', '短期減量目的だと遠回りに感じる場合'],
    pain_considerations: ['痛みを我慢させない運用があるか確認'],
    checklist_items: [
      '動作評価→説明→再現の流れがあるか',
      '専門用語を噛み砕いて説明してくれるか',
      '目的と手段の合意が取れるか',
      '自宅でできる代替案があるか',
    ],
  },
];

export const questions = [
  {
    id: 'Q-S1',
    mode: 'simple',
    type: 'single',
    prompt: '目的は？',
    options: [
      { value: 'goal_weight_loss', label: '痩せたい', traits: ['goal_weight_loss'] },
      { value: 'goal_muscle', label: '筋肉をつけたい', traits: ['goal_muscle'] },
      { value: 'goal_health', label: '健康維持', traits: ['goal_health'] },
      { value: 'goal_stress', label: 'ストレス解消', traits: ['goal_stress', 'wants_fun'] },
    ],
  },
  {
    id: 'Q-S2',
    mode: 'simple',
    type: 'single',
    prompt: '予算は？',
    options: [
      { value: 'budget_low', label: '〜7,000円/月', traits: ['budget_low'] },
      { value: 'budget_mid', label: '〜12,000円/月', traits: ['budget_mid'] },
      { value: 'budget_high', label: '〜20,000円/月', traits: ['budget_high'] },
      { value: 'budget_any', label: 'それ以上でもOK', traits: ['budget_high'] },
    ],
  },
  {
    id: 'Q-S3',
    mode: 'simple',
    type: 'single',
    prompt: '行ける時間は？',
    options: [
      { value: 'time_morning', label: '朝〜昼が多い' },
      { value: 'time_evening', label: '夕方〜夜が多い' },
      { value: 'time_late', label: '深夜/早朝が多い', traits: ['schedule_irregular'] },
      { value: 'time_irregular', label: '不規則', traits: ['schedule_irregular'] },
    ],
  },
  {
    id: 'Q-S4',
    mode: 'simple',
    type: 'single',
    prompt: '人目は気になる？',
    options: [
      { value: 'self_conscious_high', label: 'かなり気になる', traits: ['self_conscious_high'] },
      { value: 'self_conscious_mid', label: '少し気になる', traits: ['self_conscious_mid'] },
      { value: 'self_conscious_low', label: 'あまり気にならない' },
    ],
  },
  {
    id: 'Q-S5',
    mode: 'simple',
    type: 'single',
    prompt: '指導の必要度は？',
    options: [
      { value: 'needs_coaching_high', label: '教えてほしい', traits: ['needs_coaching_high'] },
      { value: 'needs_coaching_mid', label: '時々見てほしい', traits: ['needs_coaching_mid'] },
      { value: 'self_directed', label: '自分で進められる', traits: ['self_directed'] },
    ],
  },
  {
    id: 'Q-S6',
    mode: 'simple',
    type: 'single',
    prompt: '好みは？',
    options: [
      { value: 'prefers_solo', label: '黙々とやりたい', traits: ['prefers_solo'] },
      { value: 'prefers_group', label: 'クラス/みんなでやる方が続く', traits: ['prefers_group'] },
    ],
  },
  {
    id: 'Q-A1',
    mode: 'complex',
    section: '基本',
    type: 'single',
    prompt: 'いちばんの目的は？',
    options: [
      { value: 'goal_weight_loss', label: '体脂肪を落としたい', traits: ['goal_weight_loss'] },
      { value: 'goal_health', label: '体力をつけたい', traits: ['goal_health'] },
      { value: 'goal_muscle', label: '筋肉をつけたい', traits: ['goal_muscle'] },
      { value: 'goal_pain_reduce', label: '肩こり/腰の違和感を減らしたい', traits: ['goal_health', 'wants_low_intensity'] },
      { value: 'goal_stress', label: 'ストレスを減らしたい', traits: ['goal_stress', 'wants_fun'] },
    ],
  },
  {
    id: 'Q-A2',
    mode: 'complex',
    section: '基本',
    type: 'single',
    prompt: '運動経験は？',
    options: [
      { value: 'exp_none', label: 'ほぼない', traits: ['needs_coaching_high'] },
      { value: 'exp_some', label: 'たまに', traits: ['needs_coaching_mid'] },
      { value: 'exp_past_gym', label: '過去にジム経験あり', traits: ['needs_coaching_mid'] },
      { value: 'exp_current', label: 'いま何か続けている', traits: ['self_directed'] },
    ],
  },
  {
    id: 'Q-A3',
    mode: 'complex',
    section: '基本',
    type: 'multi',
    prompt: 'ジムでの不安（複数選択）',
    options: [
      { value: 'anx_menu', label: '何をすればいいか分からない', traits: ['needs_coaching_high'] },
      { value: 'anx_form', label: 'フォームが不安/ケガしそう', traits: ['needs_coaching_mid', 'pain_present'] },
      { value: 'anx_eyes', label: '人目が気になる', traits: ['self_conscious_high'] },
      { value: 'anx_continue', label: '続けられる自信がない', traits: ['needs_support'] },
      { value: 'anx_rules', label: '予約やルールが面倒そう', traits: ['reservation_hard'] },
      { value: 'anx_other', label: 'その他（任意入力）' },
    ],
  },
  {
    id: 'Q-B1',
    mode: 'complex',
    section: '生活制約',
    type: 'single',
    prompt: '週に通えそうな回数',
    options: [
      { value: 'freq_1', label: '週1' },
      { value: 'freq_2', label: '週2' },
      { value: 'freq_3', label: '週3以上' },
      { value: 'freq_unknown', label: 'まだ分からない' },
    ],
  },
  {
    id: 'Q-B2',
    mode: 'complex',
    section: '生活制約',
    type: 'single',
    prompt: '1回あたりの滞在時間',
    options: [
      { value: 'time_30', label: '30分以内', traits: ['time_short'] },
      { value: 'time_60', label: '45〜60分' },
      { value: 'time_90', label: '60〜90分' },
      { value: 'time_long', label: '90分以上' },
    ],
  },
  {
    id: 'Q-B3',
    mode: 'complex',
    section: '生活制約',
    type: 'multi',
    prompt: '通える時間帯（複数選択）',
    options: [
      { value: 'time_morning', label: '朝' },
      { value: 'time_noon', label: '昼' },
      { value: 'time_evening', label: '夕方' },
      { value: 'time_night', label: '夜' },
      { value: 'time_late', label: '深夜/早朝', traits: ['schedule_irregular'] },
      { value: 'time_irregular', label: '不定', traits: ['schedule_irregular'] },
    ],
  },
  {
    id: 'Q-B4',
    mode: 'complex',
    section: '生活制約',
    type: 'single',
    prompt: '通いやすさ',
    options: [
      { value: 'commute_must', label: '近い場所が必須' },
      { value: 'commute_prefer', label: '近い方が良い' },
      { value: 'commute_content', label: '場所より内容重視' },
    ],
  },
  {
    id: 'Q-B5',
    mode: 'complex',
    section: '生活制約',
    type: 'single',
    prompt: '支払いスタイルの好み',
    options: [
      { value: 'payg', label: '都度払い/回数券が安心', traits: ['prefers_payg'] },
      { value: 'monthly', label: '月額で通い放題がいい', traits: ['prefers_membership'] },
      { value: 'either', label: 'どちらでも' },
    ],
  },
  {
    id: 'Q-C1',
    mode: 'complex',
    section: '環境・心理',
    type: 'single',
    prompt: '人目は気になる？',
    options: [
      { value: 'self_conscious_high', label: 'かなり気になる', traits: ['self_conscious_high'] },
      { value: 'self_conscious_mid', label: '少し気になる', traits: ['self_conscious_mid'] },
      { value: 'self_conscious_low', label: '気にならない' },
    ],
  },
  {
    id: 'Q-C2',
    mode: 'complex',
    section: '環境・心理',
    type: 'single',
    prompt: '雰囲気の好み',
    options: [
      { value: 'vibe_quiet', label: '静かに黙々', traits: ['prefers_solo'] },
      { value: 'vibe_active', label: '程よく活気', traits: ['prefers_group'] },
      { value: 'vibe_lively', label: 'ワイワイ', traits: ['prefers_group'] },
    ],
  },
  {
    id: 'Q-C3',
    mode: 'complex',
    section: '環境・心理',
    type: 'single',
    prompt: '混雑への耐性',
    options: [
      { value: 'crowd_low', label: '混んでると行かなくなる' },
      { value: 'crowd_mid', label: '少しならOK' },
      { value: 'crowd_high', label: '混雑してても大丈夫' },
    ],
  },
  {
    id: 'Q-C4',
    mode: 'complex',
    section: '環境・心理',
    type: 'single',
    prompt: '予約の手間',
    options: [
      { value: 'reserve_hard', label: '予約が面倒だと続かない', traits: ['reservation_hard'] },
      { value: 'reserve_ok', label: '予約はできるが、取りづらいのは嫌', traits: ['reservation_ok'] },
      { value: 'reserve_want', label: '予約がある方が続く', traits: ['reservation_wants'] },
    ],
  },
  {
    id: 'Q-C5',
    mode: 'complex',
    section: '環境・心理',
    type: 'single',
    prompt: 'グループ/個人',
    options: [
      { value: 'prefers_solo', label: '一人でやりたい', traits: ['prefers_solo'] },
      { value: 'prefers_small_group', label: '少人数ならOK', traits: ['prefers_group', 'prefers_small_group'] },
      { value: 'prefers_group', label: 'グループが楽しい', traits: ['prefers_group'] },
    ],
  },
  {
    id: 'Q-D1',
    mode: 'complex',
    section: '指導・サポート',
    type: 'single',
    prompt: '指導の必要度',
    options: [
      { value: 'needs_coaching_high', label: 'かなり必要', traits: ['needs_coaching_high'] },
      { value: 'needs_coaching_mid', label: 'ある程度必要', traits: ['needs_coaching_mid'] },
      { value: 'self_directed', label: '基本は自分でできる', traits: ['self_directed'] },
    ],
  },
  {
    id: 'Q-D2',
    mode: 'complex',
    section: '指導・サポート',
    type: 'single',
    prompt: '食事サポート',
    options: [
      { value: 'food_yes', label: '食事も相談したい', traits: ['needs_coaching_high'] },
      { value: 'food_no', label: '運動だけでOK' },
      { value: 'food_unknown', label: '分からない' },
    ],
  },
  {
    id: 'Q-D3',
    mode: 'complex',
    section: '指導・サポート',
    type: 'single',
    prompt: 'モチベ維持のタイプ',
    options: [
      { value: 'motivation_reserved', label: '予定が決まっていると続く', traits: ['reservation_wants'] },
      { value: 'motivation_free', label: '気分で行きたい', traits: ['self_directed'] },
      { value: 'motivation_both', label: 'どちらも' },
    ],
  },
  {
    id: 'Q-E1',
    mode: 'complex',
    section: '設備・内容',
    type: 'multi',
    prompt: '何を中心にやりたい？',
    options: [
      { value: 'equip_machines', label: 'マシン（筋トレ）', traits: ['wants_machines'] },
      { value: 'equip_free', label: 'フリーウエイト', traits: ['wants_freeweights'] },
      { value: 'equip_cardio', label: '有酸素', traits: ['wants_cardio'] },
      { value: 'equip_class', label: 'クラス（スタジオ）', traits: ['wants_class', 'prefers_group'] },
      { value: 'equip_stretch', label: 'ストレッチ/体の使い方', traits: ['wants_low_intensity', 'wants_stretch'] },
      { value: 'equip_boxing', label: 'ボクササイズ等', traits: ['wants_fun'] },
    ],
  },
  {
    id: 'Q-E2',
    mode: 'complex',
    section: '設備・内容',
    type: 'multi',
    prompt: '絶対に欲しい設備',
    options: [
      { value: 'facility_shower', label: 'シャワー' },
      { value: 'facility_locker', label: '更衣室/ロッカーがしっかり' },
      { value: 'facility_pool', label: 'プール', traits: ['wants_pool_sauna', 'wants_variety'] },
      { value: 'facility_sauna', label: 'サウナ/スパ', traits: ['wants_pool_sauna', 'wants_variety'] },
      { value: 'facility_studio', label: 'スタジオ', traits: ['wants_class', 'wants_variety'] },
      { value: 'facility_none', label: '特になし' },
    ],
  },
  {
    id: 'Q-F0',
    mode: 'complex',
    section: '痛み/不調',
    type: 'single',
    prompt: '今、気になる痛み/不調はありますか？',
    options: [
      { value: 'pain_none', label: 'ない' },
      { value: 'pain_yes', label: 'ある', traits: ['pain_present'] },
    ],
    branching: { ifValue: 'pain_none', skipTo: 'Q-G1' },
  },
  {
    id: 'Q-F1',
    mode: 'complex',
    section: '痛み/不調',
    type: 'multi',
    prompt: '当てはまる状態は？',
    options: [
      { value: 'redflag_pain', label: '安静でも強い痛み/急に悪化' },
      { value: 'redflag_numb', label: 'しびれ・力が入りにくい' },
      { value: 'redflag_chest', label: '胸の痛み/強い息切れ/めまい' },
      { value: 'redflag_accident', label: '事故/転倒直後で不安' },
      { value: 'redflag_none', label: '当てはまるものはない' },
    ],
  },
  {
    id: 'Q-F2',
    mode: 'complex',
    section: '痛み/不調',
    type: 'multi',
    prompt: '痛む/気になる部位',
    options: [
      { value: 'pain_neck', label: '首' },
      { value: 'pain_shoulder', label: '肩' },
      { value: 'pain_elbow', label: '肘' },
      { value: 'pain_wrist', label: '手首' },
      { value: 'pain_back', label: '背中' },
      { value: 'pain_waist', label: '腰' },
      { value: 'pain_hip', label: '股関節' },
      { value: 'pain_knee', label: '膝' },
      { value: 'pain_ankle', label: '足首/足' },
      { value: 'pain_other', label: 'その他' },
    ],
  },
  {
    id: 'Q-F3',
    mode: 'complex',
    section: '痛み/不調',
    type: 'slider',
    prompt: '痛み/違和感の強さ',
    min: 0,
    max: 10,
    step: 1,
  },
  {
    id: 'Q-F4',
    mode: 'complex',
    section: '痛み/不調',
    type: 'single',
    prompt: '期間',
    options: [
      { value: 'pain_short', label: '2週間未満' },
      { value: 'pain_mid', label: '2〜6週間' },
      { value: 'pain_long', label: '6週間以上' },
    ],
  },
  {
    id: 'Q-F5',
    mode: 'complex',
    section: '痛み/不調',
    type: 'multi',
    prompt: '悪化しやすい動き',
    options: [
      { value: 'trigger_squat', label: 'しゃがむ/立ち上がる' },
      { value: 'trigger_run', label: '走る/ジャンプ' },
      { value: 'trigger_raise', label: '腕を上げる' },
      { value: 'trigger_twist', label: 'ひねる/振り向く' },
      { value: 'trigger_lift', label: '重い物を持つ' },
      { value: 'trigger_sit', label: '長く座る/立つ' },
      { value: 'trigger_unknown', label: '分からない' },
    ],
  },
  {
    id: 'Q-F6',
    mode: 'complex',
    section: '痛み/不調',
    type: 'multi',
    prompt: '不定愁訴',
    options: [
      { value: 'symptom_fatigue', label: '疲れやすい', traits: ['wants_low_intensity'] },
      { value: 'symptom_sleep', label: '眠りが浅い', traits: ['goal_stress'] },
      { value: 'symptom_headache', label: '頭痛が起きやすい', traits: ['wants_low_intensity'] },
      { value: 'symptom_shoulder', label: '肩こりがつらい', traits: ['wants_stretch'] },
      { value: 'symptom_stress', label: 'ストレスが強い', traits: ['goal_stress'] },
      { value: 'symptom_cold', label: '冷え/むくみ', traits: ['goal_health'] },
      { value: 'symptom_none', label: '特になし' },
    ],
  },
  {
    id: 'Q-F7',
    mode: 'complex',
    section: '痛み/不調',
    type: 'single',
    prompt: '生活への影響',
    options: [
      { value: 'impact_none', label: 'ほぼない' },
      { value: 'impact_some', label: '少しある' },
      { value: 'impact_high', label: 'かなりある' },
    ],
  },
  {
    id: 'Q-F8',
    mode: 'complex',
    section: '痛み/不調',
    type: 'single',
    prompt: '受診/治療状況',
    options: [
      { value: 'medical_current', label: '通院中/治療中' },
      { value: 'medical_past', label: '以前受診したが今はしていない' },
      { value: 'medical_none', label: '受診はしていない' },
      { value: 'medical_unknown', label: '分からない/迷っている' },
    ],
  },
  {
    id: 'Q-G1',
    mode: 'complex',
    section: 'まとめ',
    type: 'single',
    prompt: 'いちばん大事にしたいこと',
    options: [
      { value: 'priority_continue', label: 'とにかく続けやすさ', traits: ['needs_support'] },
      { value: 'priority_result', label: 'なるべく早く成果', traits: ['goal_weight_loss'] },
      { value: 'priority_privacy', label: '人目が気にならない環境', traits: ['self_conscious_high'] },
      { value: 'priority_cost', label: 'できるだけ安く', traits: ['budget_low'] },
    ],
  },
];

export const traitReasons = {
  goal_weight_loss: '減量・引き締め目的に合う',
  goal_muscle: '筋力アップに向きやすい',
  goal_health: '健康維持・体力づくり向き',
  goal_stress: 'ストレス発散しやすい',
  schedule_irregular: '時間が不規則でも通いやすい',
  budget_low: 'コストを抑えやすい',
  budget_mid: '費用と内容のバランスが良い',
  budget_high: 'サポート重視の選択肢に向く',
  prefers_solo: '黙々と自分のペースで進められる',
  prefers_group: 'クラスや仲間と続けやすい',
  self_conscious_high: '人目が気になりにくい環境を選べる',
  needs_coaching_high: 'メニューやフォームのサポートが受けやすい',
  needs_coaching_mid: 'ポイントで指導を受けやすい',
  self_directed: '自由度が高い',
  wants_class: 'クラス中心の体験がある',
  wants_fun: '楽しさ重視で続けやすい',
  wants_low_intensity: '低負荷から始めやすい',
  wants_pool_sauna: '設備の幅が広い',
  prefers_payg: '都度払いで負担が小さい',
  pain_present: '負荷調整や安全配慮を取り入れやすい',
  red_flag_maybe: '安全配慮が特に必要',
};

export const gymWeights = {
  '24h': {
    schedule_irregular: 3,
    budget_low: 2,
    prefers_solo: 2,
    self_directed: 2,
    time_short: 1,
    needs_coaching_high: -2,
    prefers_group: -1,
    pain_present: -1,
    red_flag_maybe: -2,
    prefers_payg: -1,
    wants_machines: 1,
  },
  fitness: {
    prefers_group: 2,
    wants_class: 2,
    wants_variety: 2,
    wants_pool_sauna: 2,
    goal_health: 1,
    goal_stress: 1,
    schedule_irregular: -1,
    budget_low: -1,
  },
  public: {
    budget_low: 3,
    prefers_payg: 3,
    time_short: 1,
    needs_coaching_high: -2,
    prefers_group: 0,
  },
  personal: {
    needs_coaching_high: 3,
    needs_coaching_mid: 1,
    self_conscious_high: 2,
    pain_present: 2,
    red_flag_maybe: 2,
    goal_weight_loss: 1,
    budget_low: -2,
    prefers_group: -1,
  },
  semipersonal: {
    needs_coaching_high: 1,
    needs_coaching_mid: 2,
    prefers_group: 1,
    prefers_small_group: 2,
    budget_mid: 1,
    self_conscious_high: 1,
    pain_present: 1,
    budget_low: -1,
  },
  studio: {
    prefers_group: 2,
    wants_class: 2,
    wants_low_intensity: 2,
    goal_stress: 2,
    goal_health: 1,
    wants_variety: 1,
    budget_low: -1,
  },
  combat: {
    wants_fun: 3,
    goal_stress: 2,
    goal_weight_loss: 1,
    prefers_group: 1,
    pain_present: -2,
    red_flag_maybe: -2,
  },
  conditioning: {
    pain_present: 3,
    red_flag_maybe: 3,
    wants_low_intensity: 2,
    wants_stretch: 2,
    goal_health: 2,
    self_conscious_high: 1,
    needs_coaching_high: 1,
  },
};

export const bottleneckLabels = {
  self_conscious_high: '人目が気になる',
  reservation_hard: '予約が面倒だと続かない',
  schedule_irregular: '時間が不規則',
  time_short: '時間が短くなりがち',
  needs_support: '続けられるか不安',
};

export function toScoringRules() {
  const rules = [];
  Object.entries(gymWeights).forEach(([gymTypeId, weights]) => {
    Object.entries(weights).forEach(([traitId, weight]) => {
      rules.push({ gym_type_id: gymTypeId, trait_id: traitId, weight });
    });
  });
  return rules;
}
